# Generated by Django 4.2.13 on 2024-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LaptopLoaning", "0002_laptoppin_numberoflaptops_laptoppin_uses"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptoppin",
            name="granted",
            field=models.BooleanField(default=False),
        ),
    ]
