# Generated by Django 4.2.13 on 2024-10-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_teacher_type'),
        ('LaptopLoaning', '0003_laptoppin_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoppin',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.room'),
            preserve_default=False,
        ),
    ]
