# Generated by Django 4.2.13 on 2024-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LaptopLoaning", "0004_laptoppin_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptoppin",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
