# Generated by Django 4.2.13 on 2024-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LaptopLoaning", "0005_alter_laptoppin_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptoppin",
            name="returning_time",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laptoppin",
            name="taking_time",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="laptoppin",
            name="date",
            field=models.DateField(),
        ),
    ]
