# Generated by Django 4.2.13 on 2024-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LaptopLoaning",
            "0006_laptoppin_returning_time_laptoppin_taking_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="laptoppin",
            name="reason",
            field=models.CharField(default="", max_length=255),
        ),
    ]
