# Generated by Django 4.2.13 on 2024-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LaptopLoaning", "0007_laptoppin_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptoppin",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
