# Generated by Django 4.2.13 on 2025-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopLoaning', '0008_laptoppin_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoppin',
            name='slack_ts',
            field=models.CharField(default='', max_length=255),
        ),
    ]
