# Generated by Django 4.2.13 on 2025-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopLoaning', '0009_laptoppin_slack_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptoppin',
            name='slack_ts',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
