# Generated by Django 4.2.13 on 2024-11-19 07:05

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_problem_assignee_alter_problem_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_reported',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='assignee',
            field=models.ForeignKey(default=dashboard.models.get_random_teacher, limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reporter',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 0), ('type', 2), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
