# Generated by Django 4.2.13 on 2024-11-19 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_problem_date_reported_problem_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='resolved_by',
            field=models.ForeignKey(limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='urgency',
            field=models.IntegerField(choices=[(0, 'Take Your Time'), (1, 'Urgent'), (2, 'COME RIGHT NOW!')], default=0),
        ),
    ]
