# Generated by Django 4.2.13 on 2024-11-19 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_problem_resolved_by_problem_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
