# Generated by Django 4.2.13 on 2024-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_problem_reporter_alter_problem_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='private_ts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='public_ts',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
