# Generated by Django 4.2.13 on 2024-12-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_problem_private_id_problem_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='public_id',
        ),
    ]
