# Generated by Django 4.2.13 on 2024-12-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_problem_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='reporter_guest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
