# Generated by Django 4.2.13 on 2024-07-16 08:13

from django.db import migrations
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
    ]
