# Generated by Django 5.0.6 on 2024-06-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classneedssub',
            old_name='class_name',
            new_name='Class',
        ),
    ]
