# Generated by Django 4.2.13 on 2024-07-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='language',
        ),
    ]
