# Generated by Django 4.2.13 on 2024-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_room_has_projector_room_show_as_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.IntegerField(choices=[(0, 'Teacher'), (1, 'TED'), (2, 'Management')], default=0),
        ),
    ]
