# Generated by Django 4.2.13 on 2024-08-04 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_Create_user_and_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='shocher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('grade', models.CharField(choices=[(0, 'First Grade'), (1, 'Second Grade'), (2, 'Third Grade'), (3, 'Fourth Grade'), (4, 'Fifth Grade'), (5, 'Sixth Grade'), (6, 'Seventh Grade'), (7, 'Eighth Grade'), (8, 'Ninth Grade'), (9, 'Tenth Grade'), (10, 'Eleventh Grade'), (11, 'Twelfth Grade'), (12, 'Graduate')], default='', max_length=50)),
                ('shacharit', models.ForeignKey(blank=True, limit_choices_to={'shocher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shacharit', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'tutor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
