# Generated by Django 5.0.6 on 2024-06-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_rename_class_name_classneedssub_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classneedssub',
            name='needs_sub',
        ),
        migrations.AddField(
            model_name='classneedssub',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
    ]
