# Generated by Django 5.0.6 on 2024-06-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_classneedssub_needs_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classneedssub',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
    ]
