# Generated by Django 4.2.13 on 2024-07-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_room_alter_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.room'),
        ),
    ]
