# Generated by Django 4.2.13 on 2024-12-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_teacher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classneedssub',
            name='related_absence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.absence'),
        ),
    ]
