# Generated by Django 4.2.13 on 2024-08-04 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_student_grade_alter_student_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(0, 'First Grade'), (1, 'Second Grade'), (2, 'Third Grade'), (3, 'Fourth Grade'), (4, 'Fifth Grade'), (5, 'Sixth Grade'), (6, 'Seventh Grade'), (7, 'Eighth Grade'), (8, 'Ninth Grade'), (9, 'Tenth Grade'), (10, 'Eleventh Grade'), (11, 'Twelfth Grade'), (12, 'Graduate')], default=''),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable.student')),
                ('monday_first', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_first_classes', to='timetable.class')),
                ('monday_fourth', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_fourth_classes', to='timetable.class')),
                ('monday_second', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_second_classes', to='timetable.class')),
                ('monday_third', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_third_classes', to='timetable.class')),
                ('sunday_first', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_first_classes', to='timetable.class')),
                ('sunday_fourth', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_fourth_classes', to='timetable.class')),
                ('sunday_second', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_second_classes', to='timetable.class')),
                ('sunday_third', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_third_classes', to='timetable.class')),
                ('thursday_first', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_first_classes', to='timetable.class')),
                ('thursday_fourth', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_fourth_classes', to='timetable.class')),
                ('thursday_second', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_second_classes', to='timetable.class')),
                ('thursday_third', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_third_classes', to='timetable.class')),
                ('tuesday_first', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_first_classes', to='timetable.class')),
                ('tuesday_fourth', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_fourth_classes', to='timetable.class')),
                ('tuesday_second', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_second_classes', to='timetable.class')),
                ('tuesday_third', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_third_classes', to='timetable.class')),
                ('wednesday_first', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_first_classes', to='timetable.class')),
                ('wednesday_fourth', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_fourth_classes', to='timetable.class')),
                ('wednesday_second', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_second_classes', to='timetable.class')),
                ('wednesday_third', models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_third_classes', to='timetable.class')),
            ],
        ),
    ]
