# Generated by Django 4.2.13 on 2024-09-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_schedule_teacher_alter_schedule_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
