# Generated by Django 5.0.6 on 2024-06-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_classneedssub_substitute_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classneedssub',
            old_name='Class',
            new_name='Class_That_Needs_Sub',
        ),
        migrations.AlterField(
            model_name='classneedssub',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
    ]
