# Generated by Django 4.2.13 on 2024-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_classneedssub_related_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
