# Generated by Django 4.2.13 on 2024-07-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_class_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='duration',
        ),
    ]
