# Generated by Django 4.2.13 on 2024-07-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_remove_class_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='eighth_grade',
            field=models.BooleanField(default=False, verbose_name='Eighth Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='eleventh_grade',
            field=models.BooleanField(default=False, verbose_name='Eleventh Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='fifth_grade',
            field=models.BooleanField(default=False, verbose_name='Fifth Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='first_grade',
            field=models.BooleanField(default=False, verbose_name='First Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='fourth_grade',
            field=models.BooleanField(default=False, verbose_name='Fourth Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='ninth_grade',
            field=models.BooleanField(default=False, verbose_name='Ninth Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='second_grade',
            field=models.BooleanField(default=False, verbose_name='Second Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='seventh_grade',
            field=models.BooleanField(default=False, verbose_name='Seventh Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='sixth_grade',
            field=models.BooleanField(default=False, verbose_name='Sixth Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='student_teaching',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='students_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='tenth_grade',
            field=models.BooleanField(default=False, verbose_name='Tenth Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='third_grade',
            field=models.BooleanField(default=False, verbose_name='Third Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='twelfth_grade',
            field=models.BooleanField(default=False, verbose_name='Twelfth Grade'),
        ),
    ]
