# Generated by Django 4.2.13 on 2024-06-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_rename_class_classneedssub_class_that_needs_sub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='day',
            new_name='date',
        ),
    ]
