# Generated by Django 4.2.13 on 2024-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_class_eighth_grade_class_eleventh_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student_teaching',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Teaching'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students_teacher',
            field=models.BooleanField(default=False, verbose_name='Is a Student Teaching?'),
        ),
    ]
