# Generated by Django 4.2.13 on 2024-09-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_schedule_teacher_class_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
