# Generated by Django 4.2.13 on 2024-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_teacher_slack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slack_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
