# Generated by Django 4.2.13 on 2024-08-06 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0007_rename_student_schedule_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="last_schedule_invite",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 12, 0, 34, 103786)
            ),
        ),
    ]
