# Generated by Django 4.2.13 on 2024-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_teacher_slack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slack_id',
            field=models.CharField(blank=True, default='test', max_length=255),
            preserve_default=False,
        ),
    ]
