# Generated by Django 4.2.13 on 2024-12-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_teacher_slack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slack_id',
            field=models.TextField(blank=True),
        ),
    ]
