# Generated by Django 4.2.13 on 2024-08-12 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_class_description_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_schedule_invite',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 13, 26, 2, 688872)),
        ),
    ]
