# Generated by Django 4.2.13 on 2024-08-14 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0010_alter_class_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="hour",
            field=models.TimeField(
                choices=[
                    (datetime.time(9, 15), "09:15"),
                    (datetime.time(10, 7), "10:07"),
                    (datetime.time(11, 0), "11:00"),
                    (datetime.time(11, 45), "11:45"),
                    (datetime.time(12, 45), "12:45"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_schedule_invite",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 14, 16, 54, 16, 485794)
            ),
        ),
    ]
