# Generated by Django 4.2.13 on 2024-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_teacher_slack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ted_manager',
            field=models.BooleanField(default=False),
        ),
    ]
