# Generated by Django 4.2.13 on 2024-08-15 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_alter_class_hour_alter_student_last_schedule_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='manage_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='manage_subs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_schedule_invite',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 23, 2, 27, 10441)),
        ),
    ]
