# Generated by Django 4.2.13 on 2024-08-16 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_remove_teacher_username_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_schedule_invite',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 16, 14, 8, 59, 132521)),
        ),
    ]
