# Generated by Django 4.2.13 on 2024-12-29 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_remove_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='hour',
            field=models.TimeField(choices=[(datetime.time(9, 15), '09:15'), (datetime.time(10, 7), '10:07'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 45), '11:45'), (datetime.time(12, 45), '12:45'), (datetime.time(14, 15), 'Long Day')]),
        ),
    ]
