# Generated by Django 4.2.13 on 2024-08-16 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_alter_student_last_schedule_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_schedule_invite',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 16, 11, 21, 26, 269298, tzinfo=datetime.timezone.utc)),
        ),
    ]
