# Generated by Django 4.2.13 on 2024-12-29 22:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_alter_class_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='monday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_ld_classes', to='timetable.class', verbose_name='monday ld'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_ld_classes', to='timetable.class', verbose_name='ראשון ld'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Thursday_ld_classes', to='timetable.class', verbose_name='חמישי ld'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_ld_classes', to='timetable.class', verbose_name='שלישי ld'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_ld_classes', to='timetable.class', verbose_name='רביעי ld'),
        ),
        migrations.AlterField(
            model_name='class',
            name='hour',
            field=models.TimeField(choices=[(datetime.time(9, 15), '09:15'), (datetime.time(10, 7), '10:07'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 45), '11:45'), (datetime.time(12, 45), '12:45'), (datetime.time(14, 15), 'LD')]),
        ),
    ]
