# Generated by Django 4.2.13 on 2025-01-05 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_schedule_monday_ld_schedule_sunday_ld_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='monday_first',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_first_classes', to='timetable.class', verbose_name='יום שני 09:15'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_fourth',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_fourth_classes', to='timetable.class', verbose_name='יום שני 12:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_ld_classes', to='timetable.class', verbose_name='יום שנייום ארוך'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_second',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_second_classes', to='timetable.class', verbose_name='יום שני 10:07'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_third',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_third_classes', to='timetable.class', verbose_name='יום שני 11:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_first',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_first_classes', to='timetable.class', verbose_name='יום ראשון 09:15'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_fourth',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_fourth_classes', to='timetable.class', verbose_name='יום ראשון 12:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_ld_classes', to='timetable.class', verbose_name='יום ראשוןיום ארוך'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_second',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_second_classes', to='timetable.class', verbose_name='יום ראשון 10:07'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_third',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_third_classes', to='timetable.class', verbose_name='יום ראשון 11:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_first',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_first_classes', to='timetable.class', verbose_name='יום חמישי 09:15'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Thursday_ld_classes', to='timetable.class', verbose_name='יום חמישייום ארוך'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_second',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_second_classes', to='timetable.class', verbose_name='יום חמישי 10:07'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_first',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_first_classes', to='timetable.class', verbose_name='יום שלישי 09:15'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_fourth',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_fourth_classes', to='timetable.class', verbose_name='יום שלישי 12:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_ld_classes', to='timetable.class', verbose_name='יום שלישייום ארוך'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_second',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_second_classes', to='timetable.class', verbose_name='יום שלישי 10:07'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_third',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_third_classes', to='timetable.class', verbose_name='יום שלישי 11:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_first',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(9, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_first_classes', to='timetable.class', verbose_name='יום רביעי 09:15'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_fourth',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(12, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_fourth_classes', to='timetable.class', verbose_name='יום רביעי 12:45'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_ld',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(14, 15)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_ld_classes', to='timetable.class', verbose_name='יום רביעייום ארוך'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_second',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(10, 7)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_second_classes', to='timetable.class', verbose_name='יום רביעי 10:07'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_third',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(11, 45)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_third_classes', to='timetable.class', verbose_name='יום רביעי 11:45'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slack_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
