# Generated by Django 4.2.13 on 2024-08-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_alter_student_last_schedule_invite'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
    ]
