# Generated by Django 4.2.13 on 2025-01-08 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_alter_schedule_monday_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='monday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_recess_classes', to='timetable.class', verbose_name='יום שניRecess'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_recess_classes', to='timetable.class', verbose_name='יום ראשוןRecess'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_recess_classes', to='timetable.class', verbose_name='יום חמישיRecess'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_recess_classes', to='timetable.class', verbose_name='יום שלישיRecess'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_recess_classes', to='timetable.class', verbose_name='יום רביעיRecess'),
        ),
    ]
