# Generated by Django 4.2.13 on 2025-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_schedule_monday_recess_schedule_sunday_recess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='show_in_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
