# Generated by Django 4.2.13 on 2025-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_room_show_in_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.IntegerField(default=25, verbose_name='Max Students'),
        ),
    ]
