# Generated by Django 4.2.13 on 2025-05-14 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_class_max_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='teacher',
        ),
        migrations.AddField(
            model_name='absence',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Monday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_recess_classes', to='timetable.class', verbose_name='יום שניהַפסָקָה'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Sunday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_recess_classes', to='timetable.class', verbose_name='יום ראשוןהַפסָקָה'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Thursday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_recess_classes', to='timetable.class', verbose_name='יום חמישיהַפסָקָה'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Tuesday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_recess_classes', to='timetable.class', verbose_name='יום שלישיהַפסָקָה'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_recess',
            field=models.ForeignKey(blank=True, limit_choices_to={'day_of_week': 'Wednesday', 'hour': datetime.time(11, 0)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_recess_classes', to='timetable.class', verbose_name='יום רביעיהַפסָקָה'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('absences', models.ManyToManyField(related_name='day_set', to='timetable.absence')),
            ],
        ),
    ]
