# Generated by Django 4.2.13 on 2025-05-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_remove_absence_date_remove_absence_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='teachers',
        ),
        migrations.AddField(
            model_name='absence',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
