# Generated by Django 4.2.13 on 2025-05-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_remove_absence_teachers_absence_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='absences',
        ),
        migrations.AddField(
            model_name='absence',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.day'),
            preserve_default=False,
        ),
    ]
