# Generated by Django 4.2.13 on 2025-05-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_remove_day_absences_absence_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classneedssub',
            name='related_absence',
        ),
    ]
