# Generated by Django 5.2.1 on 2025-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_remove_classneedssub_related_absence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['day_of_week', 'hour', 'room'], name='timetable_c_day_of__3c7332_idx'),
        ),
    ]
