# Generated by Django 5.2.1 on 2025-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('timetable', '0027_class_timetable_c_day_of__3c7332_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['type'], name='timetable_t_type_6a3ef5_idx'),
        ),
    ]
