# Generated by Django 5.2.1 on 2025-05-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='class',
            name='timetable_c_day_of__3c7332_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='timetable_t_type_6a3ef5_idx',
        ),
    ]
